name: Deploy blog to Github Pages

on: [push]

jobs:
  deploy:
    name: Deploy blog to Github Pages
    runs-on: ubuntu-latest
    env:
      TZ: Asia/Shanghai

    steps:
    - name: Checkout repository
      uses: actions/checkout@main

    - name: Update submodules
      run: |
        git submodule init
        git submodule update --remote

    - name: Setup Node.js
      uses: actions/setup-node@main
      with:
        node-version: "12.x"

    - name: Setup Hexo
      run: |
        npm install hexo-cli -g
        npm install

    - name: Generate
      run: |
        hexo clean
        hexo generate

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        deploy_key: ${{ secrets.GH_SSH_PRIVATE_KEY }}
        external_repository: Sakano-x/Sakano-x.github.io
        publish_branch: master
        publish_dir: ./public
        commit_message: ${{ github.event.head_commit.message }}